### ISSUE TITLE
detailed fact gathering is not working

### ISSUE THREAD

**Issue by lessfoobar** [linux-system-roles/firewall#100]
**What happened**:
TASK [linux-system-roles.firewall : Configure firewall] ************************
`failed: [192.168.88.100] (item={'detailed': True}) => {"ansible_loop_var": "item", "changed": false, "item": {"detailed": true}, "msg": "One of service, port, source_port, forward_port, masquerade, rich_rule, source, interface, icmp_block, icmp_block_inversion, target, zone or set_default_zone needs to be set"}`

**What you expected to happen**:
To get a detailed view of my firewall facts 

**How to reproduce it (as minimally and precisely as possible)**:
```
- name: Test tangd_custom_port
  hosts: 192.168.88.100
  vars:
    firewall:
      detailed: true
  tasks:
    - name: get firewall info
      import_role:
        name: linux-system-roles.firewall
```

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): firewalld-1.0.5-2.fc35.src.rpm
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): FirewallBackend= nftables
- Ansible Version (`ansible --version`): ansible [core 2.12.7]
- Firewall System Role Version (if installing from ansible galaxy `ansible-galaxy list | grep linux-system-roles.firewall` or commit hash if developing from git
`git log -n1 --format=format:"%H"`): linux-system-roles-1.20.2-1.fc35.noarch  - linux-system-roles.firewall, (unknown version)
- OS (e.g: `cat /etc/os-release`): Fedora Linux 35 (KDE Plasma)
- Others:
