### ISSUE TITLE
[docs] document `set_default_zone`

### ISSUE THREAD

**Issue by zanna-37** [linux-system-roles/firewall#105]
`set_default_zone` is a valid option, and it's working, but it is not documented in the README.

```yaml
    firewall:
      # Set default zone
      - set_default_zone: my_zone
```
