### ISSUE TITLE
Source limitation

### ISSUE THREAD

**Issue by RayMcAdmin** [linux-system-roles/firewall#23]
My team is looking to use this role but a necessary aspect of our setup requires us to limit source by zone, (effectively firewall-cmd --add-source)

Is this functionality a part of the roadmap?

(Alternatively, am I missing something that would allow this kind of configuration which is already in play?)

Any insight appreciated!

**Comment by richm** [comment]
> Is this functionality a part of the roadmap?

Yes, but not sure when it will be worked on.

**Comment by chrispoupart** [comment]
Can we submit a PR with this functionality?

**Comment by richm** [comment]
> Can we submit a PR with this functionality?

Yes - please do.

**Comment by chrispoupart** [comment]
Additional question -- is there any plan to migrate to the `ansible.posix.firewalld` module instead of maintaining the `firewall_lib` module in parallel?

This came up as our team was the work that would be required to support this functionality.  `ansible.posix.firewalld` already supports source settings, so there was some questions around why we should re-invent that.

Ideally, we would like to support this role and see it eventually included in the `rhel-system-roles`, as we are Red Hat customers.

**Comment by richm** [comment]
> Additional question -- is there any plan to migrate to the ansible.posix.firewalld module instead of maintaining the firewall_lib module in parallel?

I'm trying to find out.  It doesn't make much sense to support both the ansible.posix.firewalld and the module inside of the firewall role (the role is just a thin wrapper around the module).  I'm in touch with the firewall team and the Ansible team to find out more information.

Out of curiosity - have you tried to use the role swapping out firewall_lib with ansible.posix.firewalld?

**Comment by RayMcAdmin** [comment]
> Out of curiosity - have you tried to use the role swapping out firewall_lib with ansible.posix.firewalld?

We have now! It seems to do the trick (at least for what we need) albeit, the required parameters also needed to be updated as below;

```
- name: Configure firewall
  ansible.posix.firewalld:
    icmp_block: "{{ item.icmp_block | default(omit)}}"
    icmp_block_inversion: "{{ item.icmp_block_inversion | default(omit)}}"
    immediate: "{{ item.immediate | default(omit)}}"
    interface: "{{ item.interface | default(omit)}}"
    masqerade: "{{ item.masqerade | default(omit)}}"
    offline: "{{ item.offline | default(omit)}}"
    permanent: "{{ item.permanent | default(omit)}}"
    port: "{{ item.port | default(omit)}}"
    rich_rule: "{{ item.rich_rule | default(omit)}}"
    service: "{{ item.service | default(omit) }}"
    source: "{{ item.source | default(omit)}}"
    state: "{{ item.state }}"
    timeout: "{{ item.timeout | default(omit)}}"
    zone: "{{ item.zone | default(omit)}}"
  with_items:
    - "{{ firewall }}"
```
