### ISSUE TITLE
Installation fails with sudo user (become)

### ISSUE THREAD

**Issue by lucasteinke** [linux-system-roles/firewall#242]
**What happened**:

Running a simple playbook via `ansible-playbook -K playbooks/firewall.yml --user lucasteinke`

Fails with:

```
TASK [linux-system-roles.firewall : Install firewalld] ******************************************************************************************************************
fatal: [dev-generic.vbox.arpa]: FAILED! => changed=false 
  msg: This command has to be run under the root user.
  results: []
```

**What you expected to happen**:

That the firewall role uses my sudo privileges and the provided become password (with -K) and installs it.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
---
- name: "Set firewall rules"
  hosts: all
  roles:
    - role: linux-system-roles.firewall
  vars:
    firewall:
      - service: ssh
        state: enabled
```

run with --ask-become-pass (-K) and a different user than `root` with `--user username`.

**Environment**:
- Firewalld Version: firewalld-1.3.4-1.el9.src.rpm
- Firewalld Backend: nftables
- Ansible Version: core 2.16.11
- Firewall System Role Version: 1.8.0
- target OS: Red Hat Enterprise Linux 9
- Ansible OS: Fedora 40
