### ISSUE TITLE
Add `includes` when defining a custom service

### ISSUE THREAD

**Issue by skwde** [linux-system-roles/firewall#255]
**What would you like to be added**:

Allow for `includes` when defining a custom service (https://firewalld.org/documentation/man-pages/firewalld.service.html), e.g.

```yml
        - name: Run firewall role
          ansible.builtin.include_role:
            name: fedora.linux_system_roles.firewall
          vars:
            firewall_disable_conflicting_services: true
            firewall:
              - service: custom
                short: Custom
                description: Custom service
                port: 2222/tcp
                includes: [http, https]
                state: present
                permanent: true
```

Currently `includes` are silently ignored.

An example is e.g. the predefined firewalld service `freeipa-4` (https://github.com/firewalld/firewalld/blob/main/config/services/freeipa-4.xml)

**Why is this needed**:

This makes firewalld services more explicit and easier / quicker to read when there are many non-standard ports.
