### ISSUE TITLE
setting service helper is broken

### ISSUE THREAD

**Issue by martinpitt** [linux-system-roles/firewall#276]
**issue (bug_risk):** Missing negation when checking helper module existence

Use `if not fw_service_settings.queryModule(_module):` so you only add modules that don’t already exist.

_Originally posted by @sourcery-ai[bot] in https://github.com/linux-system-roles/firewall/pull/274#discussion_r2095692322_

**Comment by martinpitt** [comment]
The code is broken, the helper isn't set:

```
# firewall-cmd --permanent --info-service customservice
customservice
  ports: 333/tcp
  protocols: ipv6
  source-ports: 333/tcp
  modules: 
  destination: ipv4:123.45.6.78 ipv6:aaaa:aaaa:aaaa:aaa:aaaa:aaaa:aaaa::
  includes: https ldaps
  helpers: 
```

The test does not spot it because it does not actually validate the setting on the firewalld backend.
