### ISSUE TITLE
When use redhat.rhel_system_roles.firewall under bootc image mode, playbook failed

### ISSUE THREAD

**Issue by rhui** [linux-system-roles/firewall#282]
**What happened**:
When use redhat.rhel_system_roles.firewall under bootc image mode, playbook failed

**What you expected to happen**:
The playbook should complete without error

**How to reproduce it (as minimally and precisely as possible)**:
Here is the containerfile 
```
FROM registry.redhat.io/rhel10/rhel-bootc:latest
RUN dnf -y install ansible-core rhel-system-roles firewalld tree
COPY ./files/fw-playbook.yml .
RUN ansible-playbook fw-playbook.yml
```
cat files/fw-playbook.yml

```
- name: Create firewalld
  hosts: localhost
  tasks:
    - name:
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.firewall
      vars:
        firewall:
          - service: customservice
            short: Custom Service
            description: Custom service for example purposes
            port: ["22/tcp", "9090/tcp", "81616/tcp", "61616/tcp"]
            state: enabled
            permanent: yes
```

resulting 
```
TASK [redhat.rhel_system_roles.firewall : Unmask firewalld service] ************
skipping: [localhost]

TASK [redhat.rhel_system_roles.firewall : Enable and start firewalld service] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service firewalld: host"}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
```

[basic-log.txt](https://github.com/user-attachments/files/20860797/basic-log.txt)
[detail-log.txt](https://github.com/user-attachments/files/20860799/detail-log.txt)
