### ISSUE TITLE
Ansible Facts for Firewall Settings

### ISSUE THREAD

**Issue by vrindle** [linux-system-roles/firewall#82]
**What would you like to be added**:
Implement Ansible Facts for the Firewall System Role.
**Why is this needed**:
This feature is needed to provide users information regarding the remote systems that they are connected with using the Firewall System Role.

**Comment by BrennanPaciorek** [comment]
So the goal here is to just display all ansible facts to the user when they use the firewall system role?

**Comment by richm** [comment]
> So the goal here is to just display all ansible facts to the user when they use the firewall system role, or to make them accessible to the user without them needing to specify anything besides the firewall system role?

The user should be able to "call" the firewall role with no arguments, and the firewall role should return the current configuration in a form that can be used to call the firewall role again, using the variable `firewall_config`:

```yaml
- name: Get current firewall config
  include_role:
    name: linux-system-roles.firewall
  vars:
    firewall:

- name: Show firewall config
  debug:
    msg: firewall_config {{ firewall_config | to_nice_json }}
```
The internal representation of `firewall_config` is like `firewall` - a `list` of `dict` values.  The user can then print or format these in any way they want.

`firewall_config` should be documented in the README.md as a variable that can be "returned" by the role - similar to https://github.com/linux-system-roles/kernel_settings#variables-exported-by-the-role

One tricky part is - do we include the default values or not?  That is, if you install firewalld, it comes with a pre-set list of zones, services, etc. - do we return those in `firewall_config`?  Or only values that have been customized by the user?  IMO, it should be the latter.

**Comment by vrindle** [comment]
> One tricky part is - do we include the default values or not? That is, if you install firewalld, it comes with a pre-set list of zones, services, etc. - do we return those in `firewall_config`? Or only values that have been customized by the user? IMO, it should be the latter.

Maybe we could do both? Show the values that have been customized by the user but still also show the other pre-set list of things that come with firewalld. We could differentiate it when displaying the output to the users.

**Comment by richm** [comment]
> > One tricky part is - do we include the default values or not? That is, if you install firewalld, it comes with a pre-set list of zones, services, etc. - do we return those in `firewall_config`? Or only values that have been customized by the user? IMO, it should be the latter.
> 
> Maybe we could do both? Show the values that have been customized by the user but still also show the other pre-set list of things that come with firewalld. We could differentiate it when displaying the output to the users.

The role won't "display" output to users.  Maybe something like this (using YAML format for illustration purposes - real format will be `dict` of `lists` of `dicts`:
```yaml
firewall_config:
  defaults:
    - zone: default
      service: ssh
    ....
  custom:
    - zone: mycustomzone
      state: present
    ....
```
or something like that
