### ISSUE TITLE
forward_port should accept list of string or list of dict

### ISSUE THREAD

**Issue by BrennanPaciorek** [linux-system-roles/firewall#85]
**What happened**:
`forward_port` argument validation does not accept dictionary argument
**What you expected to happen**:
`forward_port` functionality to work when using a dictionary argument instead of a string, which is the deprecated format
**How to reproduce it (as minimally and precisely as possible)**:
```yaml
firewall:
  forward_port:
    - port: [any port]
      proto: [tcp/udp]
```
**Anything else we need to know?**:
No
